project:
  type: website
  output-dir: _site
  resources:
    - "assets/**"
    - "courses/**/*.js"
execute:
  freeze: auto
website:
  title: "Uzuki-Lab"
  navbar:
    background: primary
    search: true
    left:
      - text: "研究"
        href: research/index.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - section: "講義"
        contents:
          - section: "栽培施設学"
            href: courses/facility/index.qmd
          - section: "スマート農業"
            collapse-level: 0
            contents:
              - text: "概要"
                href: courses/smart-ag/index.qmd
              - text: "2値化処理"
                href: courses/smart-ag/binarization.qmd
              - text: "カラー画像の仕組み"
                href: courses/smart-ag/color.qmd
              - text: "エッジ検出"
                href: courses/smart-ag/edge.qmd
              - text: "分光分析"
                href: courses/smart-ag/spectral.qmd
          - section: "Ｒ講座"
            href: courses/r-course/index.qmd
          - section: "統計基礎"
            href: courses/stats/index.qmd
format:
  html:
    code-tools: false
    code-fold: false
    theme: cosmo
    css: assets/css/styles.css
    toc: true
    lang: ja