project:
  type: website
  output-dir: _site
  
website:
  title: "Uzuki Laboratory"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "講義"
        menu:
          - text: "栽培施設学"
            href: courses/facility/index.qmd
          - text: "スマート農業"
            menu:  # スマート農業にサブメニューを追加
              - text: "概要"
                href: courses/smart-ag/index.qmd
              - text: "画像処理の基礎"
                href: courses/smart-ag/image-processing/index.qmd
              - text: "分光分析"
                href: courses/smart-ag/spectral-analysis/index.qmd
          - text: "R講座"
            href: courses/r-course/index.qmd
          - text: "統計講座"
            href: courses/stats/index.qmd
      - text: "研究"
        href: research/index.qmd
format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true
    lang: ja
    
execute:
  freeze: auto